#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

. ./config.sh

get_code_url="https://bitbucket.org/site/oauth2/authorize?client_id=$key&response_type=code"
get_access_token_url="https://bitbucket.org/site/oauth2/access_token"

get_code() {
    echo "Open in a browser, and grant access if not yet done: $get_code_url"
    read -p 'What is the code in the URL you are redirected to? ' code
}

get_access_token() {
    curl -s -X POST -u "$key:$secret" "$get_access_token_url" -d grant_type=authorization_code -d "code=$code"
}

save_access_token() {
    local json=$1
    local token=$(jq -r .access_token <<< "$json")
    {
        echo "# file: $token_sh_file"
        echo "# generated by: $0"
        echo "token=$token"
    } | tee "$token_sh_file"
}

get_code

access_token_json=$(get_access_token)

jq . <<< "$access_token_json"

save_access_token "$access_token_json"
